---
- name: Remove legacy yum repo file if present
  ansible.builtin.yum_repository:
    file: cernvm.repo
    name: "{{ item }}"
    state: absent
  loop:
    - cernvm
    - cernvm-config

- name: Configure CernVM yum repositories
  ansible.builtin.yum_repository:
    file: cernvm
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CernVM
    gpgcheck: true
    enabled: true
    protect: true
  loop: "{{ cvmfs_dnf_repos }}"

- name: Install CernVM yum key
  ansible.builtin.copy:
    content: "{{ cvmfs_dnf_repo_key.content }}"
    dest: "{{ cvmfs_dnf_repo_key.dest }}"
    owner: root
    group: root
    mode: "0644"

- name: Install CernVM-FS packages and dependencies (yum)
  ansible.builtin.yum:
    name: "{{ cvmfs_packages[_cvmfs_role] | reject('equalto', omit) | list }}"
    state: "{{ 'latest' if _cvmfs_upgrade else 'present' }}"
